namespace Serverside.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class CrimeBot : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.CrimeBot", "Vehicle", c => c.Int(nullable: false));
            AddColumn("dbo.CrimeBot", "Model", c => c.Int(nullable: false));
            AddColumn("dbo.CrimeBot", "PistolCost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "PistolCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "PistolDefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "PistolMk2Cost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "PistolMk2Count", c => c.Int());
            AddColumn("dbo.CrimeBot", "PistolMk2rDefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "CombatPistolCost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "CombatPistolCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "CombatPistolDefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "Pistol50Cost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "Pistol50Count", c => c.Int());
            AddColumn("dbo.CrimeBot", "Pistol50DefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "SNSPistolCost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "SNSPistolCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "SNSPistolDefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "HeavyPistolCost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "HeavyPistolCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "HeavyPistolDefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "RevolverCost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "RevolverCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "RevolverDefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "MicroSMGCost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "MicroSMGCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "MicroSMGDefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "SMGCost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "SMGCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "SMGDefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "SMGMk2Cost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "SMGMk2Count", c => c.Int());
            AddColumn("dbo.CrimeBot", "SMGMk2DefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "MiniSMGCost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "MiniSMGCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "MiniSMGDefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "AssaultRifleCost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "AssaultRifleCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "AssaultRifleDefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "AssaultRifleMk2Cost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "AssaultRifleMk2Count", c => c.Int());
            AddColumn("dbo.CrimeBot", "AssaultRifleMk2DefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "SniperRifleCost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "SniperRifleCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "SniperRifleDefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "DoubleBarrelShotgunCost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "DoubleBarrelShotgunCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "DoubleBarrelShotgunDefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "PumpShotgunCost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "PumpShotgunCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "PumpShotgunDefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "SawnoffShotgunCost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "SawnoffShotgunCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "SawnoffShotgunDefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "PistolMagazineCost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "PistolMagazineCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "PistolMagazineDefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "PistolMk2MagazineCost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "PistolMk2MagazineCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "PistolMk2rMagazineDefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "CombatPistolMagazineCost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "CombatPistolMagazineCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "CombatPistolMagazineDefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "Pistol50MagazineCost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "Pistol50MagazineCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "Pistol50MagazineDefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "SNSPistolMagazineCost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "SNSPistolMagazineCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "SNSPistolMagazineDefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "HeavyPistolMagazineCost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "HeavyPistolMagazineCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "HeavyPistolMagazineDefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "RevolverMagazineCost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "RevolverMagazineCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "RevolverMagazineDefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "MicroSMGMagazineCost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "MicroSMGMagazineCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "MicroSMGMagazineDefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "SMGMagazineCost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "SMGMagazineCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "SMGMagazineDefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "SMGMk2MagazineCost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "SMGMk2MagazineCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "SMGMk2MagazineDefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "MiniSMGMagazineCost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "MiniSMGMagazineCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "MiniSMGMagazineDefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "AssaultRifleMagazineCost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "AssaultRifleMagazineCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "AssaultRifleMagazineDefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "AssaultRifleMk2MagazineCost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "AssaultRifleMk2MagazineCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "AssaultRifleMk2MagazineDefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "SniperRifleMagazineCost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "SniperRifleMagazineCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "SniperRifleMagazineDefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "DoubleBarrelShotgunMagazineCost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "DoubleBarrelShotgunMagazineCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "DoubleBarrelShotgunMagazineDefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "PumpShotgunMagazineCost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "PumpShotgunMagazineCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "PumpShotgunMagazineDefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "SawnoffShotgunMagazineCost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "SawnoffShotgunMagazineCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "SawnoffShotgunMagazineDefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "MarijuanaCost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "MarijuanaCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "MarijuanaDefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "LsdCost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "LsdCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "LsdDefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "ExcstasyCost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "ExcstasyCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "ExcstasyDefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "AmphetamineCost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "AmphetamineCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "AmphetamineDefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "MetaamphetamineCost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "MetaamphetamineCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "MetaamphetamineDefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "CrackCost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "CrackCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "CrackDefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "CocaineCost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "CocaineCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "CocaineDefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "HasishCost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "HasishCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "HasishDefaultCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "HeroinCost", c => c.Decimal(precision: 18, scale: 2));
            AddColumn("dbo.CrimeBot", "HeroinCount", c => c.Int());
            AddColumn("dbo.CrimeBot", "HeroinDefaultCount", c => c.Int());
        }
        
        public override void Down()
        {
            DropColumn("dbo.CrimeBot", "HeroinDefaultCount");
            DropColumn("dbo.CrimeBot", "HeroinCount");
            DropColumn("dbo.CrimeBot", "HeroinCost");
            DropColumn("dbo.CrimeBot", "HasishDefaultCount");
            DropColumn("dbo.CrimeBot", "HasishCount");
            DropColumn("dbo.CrimeBot", "HasishCost");
            DropColumn("dbo.CrimeBot", "CocaineDefaultCount");
            DropColumn("dbo.CrimeBot", "CocaineCount");
            DropColumn("dbo.CrimeBot", "CocaineCost");
            DropColumn("dbo.CrimeBot", "CrackDefaultCount");
            DropColumn("dbo.CrimeBot", "CrackCount");
            DropColumn("dbo.CrimeBot", "CrackCost");
            DropColumn("dbo.CrimeBot", "MetaamphetamineDefaultCount");
            DropColumn("dbo.CrimeBot", "MetaamphetamineCount");
            DropColumn("dbo.CrimeBot", "MetaamphetamineCost");
            DropColumn("dbo.CrimeBot", "AmphetamineDefaultCount");
            DropColumn("dbo.CrimeBot", "AmphetamineCount");
            DropColumn("dbo.CrimeBot", "AmphetamineCost");
            DropColumn("dbo.CrimeBot", "ExcstasyDefaultCount");
            DropColumn("dbo.CrimeBot", "ExcstasyCount");
            DropColumn("dbo.CrimeBot", "ExcstasyCost");
            DropColumn("dbo.CrimeBot", "LsdDefaultCount");
            DropColumn("dbo.CrimeBot", "LsdCount");
            DropColumn("dbo.CrimeBot", "LsdCost");
            DropColumn("dbo.CrimeBot", "MarijuanaDefaultCount");
            DropColumn("dbo.CrimeBot", "MarijuanaCount");
            DropColumn("dbo.CrimeBot", "MarijuanaCost");
            DropColumn("dbo.CrimeBot", "SawnoffShotgunMagazineDefaultCount");
            DropColumn("dbo.CrimeBot", "SawnoffShotgunMagazineCount");
            DropColumn("dbo.CrimeBot", "SawnoffShotgunMagazineCost");
            DropColumn("dbo.CrimeBot", "PumpShotgunMagazineDefaultCount");
            DropColumn("dbo.CrimeBot", "PumpShotgunMagazineCount");
            DropColumn("dbo.CrimeBot", "PumpShotgunMagazineCost");
            DropColumn("dbo.CrimeBot", "DoubleBarrelShotgunMagazineDefaultCount");
            DropColumn("dbo.CrimeBot", "DoubleBarrelShotgunMagazineCount");
            DropColumn("dbo.CrimeBot", "DoubleBarrelShotgunMagazineCost");
            DropColumn("dbo.CrimeBot", "SniperRifleMagazineDefaultCount");
            DropColumn("dbo.CrimeBot", "SniperRifleMagazineCount");
            DropColumn("dbo.CrimeBot", "SniperRifleMagazineCost");
            DropColumn("dbo.CrimeBot", "AssaultRifleMk2MagazineDefaultCount");
            DropColumn("dbo.CrimeBot", "AssaultRifleMk2MagazineCount");
            DropColumn("dbo.CrimeBot", "AssaultRifleMk2MagazineCost");
            DropColumn("dbo.CrimeBot", "AssaultRifleMagazineDefaultCount");
            DropColumn("dbo.CrimeBot", "AssaultRifleMagazineCount");
            DropColumn("dbo.CrimeBot", "AssaultRifleMagazineCost");
            DropColumn("dbo.CrimeBot", "MiniSMGMagazineDefaultCount");
            DropColumn("dbo.CrimeBot", "MiniSMGMagazineCount");
            DropColumn("dbo.CrimeBot", "MiniSMGMagazineCost");
            DropColumn("dbo.CrimeBot", "SMGMk2MagazineDefaultCount");
            DropColumn("dbo.CrimeBot", "SMGMk2MagazineCount");
            DropColumn("dbo.CrimeBot", "SMGMk2MagazineCost");
            DropColumn("dbo.CrimeBot", "SMGMagazineDefaultCount");
            DropColumn("dbo.CrimeBot", "SMGMagazineCount");
            DropColumn("dbo.CrimeBot", "SMGMagazineCost");
            DropColumn("dbo.CrimeBot", "MicroSMGMagazineDefaultCount");
            DropColumn("dbo.CrimeBot", "MicroSMGMagazineCount");
            DropColumn("dbo.CrimeBot", "MicroSMGMagazineCost");
            DropColumn("dbo.CrimeBot", "RevolverMagazineDefaultCount");
            DropColumn("dbo.CrimeBot", "RevolverMagazineCount");
            DropColumn("dbo.CrimeBot", "RevolverMagazineCost");
            DropColumn("dbo.CrimeBot", "HeavyPistolMagazineDefaultCount");
            DropColumn("dbo.CrimeBot", "HeavyPistolMagazineCount");
            DropColumn("dbo.CrimeBot", "HeavyPistolMagazineCost");
            DropColumn("dbo.CrimeBot", "SNSPistolMagazineDefaultCount");
            DropColumn("dbo.CrimeBot", "SNSPistolMagazineCount");
            DropColumn("dbo.CrimeBot", "SNSPistolMagazineCost");
            DropColumn("dbo.CrimeBot", "Pistol50MagazineDefaultCount");
            DropColumn("dbo.CrimeBot", "Pistol50MagazineCount");
            DropColumn("dbo.CrimeBot", "Pistol50MagazineCost");
            DropColumn("dbo.CrimeBot", "CombatPistolMagazineDefaultCount");
            DropColumn("dbo.CrimeBot", "CombatPistolMagazineCount");
            DropColumn("dbo.CrimeBot", "CombatPistolMagazineCost");
            DropColumn("dbo.CrimeBot", "PistolMk2rMagazineDefaultCount");
            DropColumn("dbo.CrimeBot", "PistolMk2MagazineCount");
            DropColumn("dbo.CrimeBot", "PistolMk2MagazineCost");
            DropColumn("dbo.CrimeBot", "PistolMagazineDefaultCount");
            DropColumn("dbo.CrimeBot", "PistolMagazineCount");
            DropColumn("dbo.CrimeBot", "PistolMagazineCost");
            DropColumn("dbo.CrimeBot", "SawnoffShotgunDefaultCount");
            DropColumn("dbo.CrimeBot", "SawnoffShotgunCount");
            DropColumn("dbo.CrimeBot", "SawnoffShotgunCost");
            DropColumn("dbo.CrimeBot", "PumpShotgunDefaultCount");
            DropColumn("dbo.CrimeBot", "PumpShotgunCount");
            DropColumn("dbo.CrimeBot", "PumpShotgunCost");
            DropColumn("dbo.CrimeBot", "DoubleBarrelShotgunDefaultCount");
            DropColumn("dbo.CrimeBot", "DoubleBarrelShotgunCount");
            DropColumn("dbo.CrimeBot", "DoubleBarrelShotgunCost");
            DropColumn("dbo.CrimeBot", "SniperRifleDefaultCount");
            DropColumn("dbo.CrimeBot", "SniperRifleCount");
            DropColumn("dbo.CrimeBot", "SniperRifleCost");
            DropColumn("dbo.CrimeBot", "AssaultRifleMk2DefaultCount");
            DropColumn("dbo.CrimeBot", "AssaultRifleMk2Count");
            DropColumn("dbo.CrimeBot", "AssaultRifleMk2Cost");
            DropColumn("dbo.CrimeBot", "AssaultRifleDefaultCount");
            DropColumn("dbo.CrimeBot", "AssaultRifleCount");
            DropColumn("dbo.CrimeBot", "AssaultRifleCost");
            DropColumn("dbo.CrimeBot", "MiniSMGDefaultCount");
            DropColumn("dbo.CrimeBot", "MiniSMGCount");
            DropColumn("dbo.CrimeBot", "MiniSMGCost");
            DropColumn("dbo.CrimeBot", "SMGMk2DefaultCount");
            DropColumn("dbo.CrimeBot", "SMGMk2Count");
            DropColumn("dbo.CrimeBot", "SMGMk2Cost");
            DropColumn("dbo.CrimeBot", "SMGDefaultCount");
            DropColumn("dbo.CrimeBot", "SMGCount");
            DropColumn("dbo.CrimeBot", "SMGCost");
            DropColumn("dbo.CrimeBot", "MicroSMGDefaultCount");
            DropColumn("dbo.CrimeBot", "MicroSMGCount");
            DropColumn("dbo.CrimeBot", "MicroSMGCost");
            DropColumn("dbo.CrimeBot", "RevolverDefaultCount");
            DropColumn("dbo.CrimeBot", "RevolverCount");
            DropColumn("dbo.CrimeBot", "RevolverCost");
            DropColumn("dbo.CrimeBot", "HeavyPistolDefaultCount");
            DropColumn("dbo.CrimeBot", "HeavyPistolCount");
            DropColumn("dbo.CrimeBot", "HeavyPistolCost");
            DropColumn("dbo.CrimeBot", "SNSPistolDefaultCount");
            DropColumn("dbo.CrimeBot", "SNSPistolCount");
            DropColumn("dbo.CrimeBot", "SNSPistolCost");
            DropColumn("dbo.CrimeBot", "Pistol50DefaultCount");
            DropColumn("dbo.CrimeBot", "Pistol50Count");
            DropColumn("dbo.CrimeBot", "Pistol50Cost");
            DropColumn("dbo.CrimeBot", "CombatPistolDefaultCount");
            DropColumn("dbo.CrimeBot", "CombatPistolCount");
            DropColumn("dbo.CrimeBot", "CombatPistolCost");
            DropColumn("dbo.CrimeBot", "PistolMk2rDefaultCount");
            DropColumn("dbo.CrimeBot", "PistolMk2Count");
            DropColumn("dbo.CrimeBot", "PistolMk2Cost");
            DropColumn("dbo.CrimeBot", "PistolDefaultCount");
            DropColumn("dbo.CrimeBot", "PistolCount");
            DropColumn("dbo.CrimeBot", "PistolCost");
            DropColumn("dbo.CrimeBot", "Model");
            DropColumn("dbo.CrimeBot", "Vehicle");
        }
    }
}
